name: e2e Test Run

on: 
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs: 
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run e2e tests
        run: | 
          docker compose -f testing/compose.yml up -d --build
          docker run --rm -v ./e2e:/app -w /app --network=e2e-testing_e2e-testing --entrypoint cypress cypress/included:12.13.0 run -b firefox --config baseUrl=http://app:8080,video=false,screenshotOnRunFailure=false
          docker compose -f testing/compose.yml down