name: e2e Test Run

on: 
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs: 
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start app for e2e testing
        run: docker compose -f testing/compose.yml up -d --build

      - name: Install Dependencies
        run: npm install
        working-directory: ./e2e

      - name: Run e2e Tests (Cypress)
        uses: cypress-io/github-action@v6
        with:
          browser: firefox
          wait-on: http://localhost:8080
          config-file: ./e2e/cypress.json
          project: ./e2e
          config: baseUrl=http://localhost:8080,video=false,screenshotOnRunFailure=false

      - name: Stop app after e2e testing
        if: always()
        run: docker compose -f testing/compose.yml down